image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - before: |
      cd /workspace && git clone https://github.com/leanprover-community/lean4game.git && cd /workspace/lean4game && npm install
  - init: |
      lake update && lake exe cache get && lake build
