name: Export
run-name: Export
on: [workflow_dispatch]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export into Game Server
        run: wget https://adam.math.hhu.de/import/trigger/$GITHUB_REPOSITORY --no-check-certificate

      - name: View Progress
        run: echo "View progress at https://adam.math.hhu.de/import/status/$GITHUB_REPOSITORY"
